version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SECRET_KEY: 'your_production_secret_key'
      DJANGO_SETTINGS_MODULE: 'pdf_translator_web.settings'
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
