version: 1
disable_existing_loggers: false

formatters:
  verbose:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  simple:
    format: '%(levelname)s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple

  file:
    class: logging.FileHandler
    formatter: verbose
    filename: logs/django.log
    level: DEBUG

  pdf_processing_file:
    class: logging.FileHandler
    formatter: verbose
    filename: logs/pdf_processing.log
    level: INFO

  translation_model_file:
    class: logging.FileHandler
    formatter: verbose
    filename: logs/translation_model.log
    level: INFO

  text_processing_file:
    class: logging.FileHandler
    formatter: verbose
    filename: logs/text_processing.log
    level: INFO

loggers:
  django:
    handlers: ['console', 'file']
    level: DEBUG
    propagate: true

  pdf_processing:
    handlers: ['console', 'pdf_processing_file']
    level: INFO
    propagate: true

  translation_model:
    handlers: ['console', 'translation_model_file']
    level: INFO
    propagate: true

  text_processing:
    handlers: ['console', 'text_processing_file']
    level: INFO
    propagate: true
